spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:shared
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties.hibernate:
      format_sql: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB